config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :users
  resources :favorites

  root "favorites#index"

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  # BELONGS_TO ==> informa que o Favorite tem um User|Movie, no singular.
  # Assim permitindo acessar o pai, mas não o inverso sem o "has_many"
  belongs_to :user
  belongs_to :movie

  before_validation :seta_data_criacao, on: :create
  before_validation :seta_data_atualizacao, :verfica_unico_registro

  def seta_data_criacao
    self.created_at = Time.now
  end

  def seta_data_atualizacao
    self.updated_at = Time.now
  end

  def verfica_unico_registro
    if Favorite.where(movie_id: self.movie_id, user_id: self.user_id).count > 0
      # error.add :nomeDoAtributo, :mensagemDeErro
      errors.add(:base, "Já existe um registro para este filme e usuário")
    end
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  # O nome do outro modelo é PLURALIZADO ao declarar uma has_many associação.
  # Quando usado com o belongs_to tem uma relação de um para muitos BIDIRECIONAL.
  has_many :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  # O nome do outro modelo é PLURALIZADO ao declarar uma has_many associação.
  # Quando usado com o belongs_to tem uma relação de um para muitos BIDIRECIONAL.
  has_many :favorites

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true, on: :create
  validates :gender, length: { maximum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
    @movies = Movie.all
    @users = User.all
  end

  # GET /favorites/1/edit
  def edit
    renderiza :edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)
    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: "Favorite was successfully created." }
        format.json { render :show, status: :created, location: @favorite }
      else
        @movies = Movie.all
        @users = User.all
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: "Favorite was successfully updated." }
        format.json { render :show, status: :ok, location: @favorite }
      else
        puts @favorite.errors.inspect
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: "Favorite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_favorite
    @favorite = Favorite.find(params[:id])
    @movies = Movie.all
    @users = User.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def favorite_params
    params.fetch(:favorite, {}).permit(:movie_id, :user_id)
  end

  def renderiza(view)
    @favorite = Favorite.find(params[:id])
    @movies = Movie.all
    @users = User.all

    render view
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :lengt, :release_dt, :synopsis)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :gender, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>
      <ul>
        <% @favorite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <div class="row">
      <div class="col-sm-2">
        <div class="form-group">
          <%= f.label "Filme" %>
          <%= f.collection_select :movie_id, @movies, :id, :name, {}, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <div class="form-group">
          <%= f.label "Usuario" %>
          <%= f.collection_select :user_id, @users.all, :id, :username, {}, class: "form-control" %>
        </div>
      </div>
    </div>
    <%= f.submit class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>
<%= render 'form' %>
<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Favorites</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome do filme</th>
      <th>Email do usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.movie.name %></td>
        <td><%= favorite.user.email %></td>
        <td><%= link_to "Show", favorite, class: "btn btn-primary" %></td>
        <td><%= link_to "Edit", edit_favorite_path(favorite), class: "btn btn-primary" %></td>
        <td><%= link_to "Destroy", favorite, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger " %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Favorite", new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>
      <ul>
        <% @favorite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label "id:" %>
        <%= @favorite.id %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label "Nome do filme:" %>
        <%= @favorite.movie.name %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label "Email do usuário:" %>
        <%= @favorite.user.email %>
      </div>
    </div>
  </div>
<% end %>
<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locadora</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="container ">
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :lengt %>
        <%= f.text_field :lengt, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :release_dt %>
        <%= f.date_select :release_dt, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :synopsis %>
        <%= f.text_area :synopsis, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class:" btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Movies</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Lengt</th>
      <th>Release dt</th>
      <th>Synopsis</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.lengt %></td>
        <td><%= movie.release_dt %></td>
        <td><%= movie.synopsis %></td>
        <td><%= link_to 'Show', movie, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) , class: "btn btn-primary"%></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Lengt:</strong>
  <%= @movie.lengt %>
</p>

<p>
  <strong>Release dt:</strong>
  <%= @movie.release_dt %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :gender %>
        <%= f.text_field :gender, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary btn-sm"  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Users</h1>
<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Gender</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary"%></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>